export * from "./contentAdvantages";
export * from "./contentCapabilities";
export * from "./contentPartner";
export * from "./defaultProps";
export * from "./featureImage";
export * from "./prices";
export * from "./team";
export * from "./utils";
export * from "./contentAdvantages.data";
export * from "./contentCapabilities.data";
export * from "./contentPartner.data";
export * from "./prices.data";
export { default } from "./MainPage";
